services:
  - type: web
    name: hesocial-backend
    env: node
    plan: free
    repo: https://github.com/yanggoufang/hesocial
    branch: master
    rootDir: backend
    buildFilter:
      paths:
      - backend/**
    build_command: "npm install && npm run build"
    start_command: "npm start"
    env_vars:
      - key: DATABASE_URL
        fromDatabase:
          name: hesocial-db
          property: connectionString
      - key: NODE_VERSION
        value: 20.11.1

  - type: web
    name: hesocial-frontend
    env: static
    plan: free
    repo: https://github.com/yanggoufang/hesocial
    branch: master
    rootDir: frontend
    buildFilter:
      paths:
      - frontend/**
    build_command: "npm install && npm run build"
    static_publish_path: "dist"
    env_vars:
      - key: NODE_VERSION
        value: 20.11.1

databases:
  - name: hesocial-db
    plan: free
    databaseName: hesocial
    user: hesocial
